# Generated by Django 4.2.11 on 2026-05-08 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(default='TechZone', max_length=200)),
                ('store_tagline', models.CharField(blank=True, default='Computers, Laptops & Accessories', max_length=300)),
                ('store_email', models.EmailField(blank=True, default='info@techzone.co.ke', max_length=254)),
                ('store_phone', models.CharField(blank=True, default='+254 700 000 000', max_length=20)),
                ('address_line', models.CharField(blank=True, max_length=300)),
                ('city', models.CharField(blank=True, default='Nairobi', max_length=100)),
                ('country', models.CharField(blank=True, default='Kenya', max_length=100)),
                ('currency_code', models.CharField(default='KES', max_length=5)),
                ('currency_symbol', models.CharField(default='KSh', max_length=5)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='settings/')),
                ('facebook_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('mpesa_enabled', models.BooleanField(default=True)),
                ('mpesa_environment', models.CharField(choices=[('sandbox', 'Sandbox (Testing)'), ('production', 'Production (Live)')], default='sandbox', max_length=20)),
                ('mpesa_consumer_key', models.CharField(blank=True, max_length=200)),
                ('mpesa_consumer_secret', models.CharField(blank=True, max_length=200)),
                ('mpesa_shortcode', models.CharField(blank=True, max_length=20)),
                ('mpesa_passkey', models.CharField(blank=True, max_length=200)),
                ('mpesa_callback_url', models.URLField(blank=True)),
                ('default_shipping_cost', models.DecimalField(decimal_places=2, default=300, max_digits=10)),
                ('free_shipping_threshold', models.DecimalField(decimal_places=2, default=10000, help_text='Orders above this amount get free shipping. Set 0 to disable.', max_digits=10)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=16.0, help_text='VAT percentage', max_digits=5)),
                ('tax_inclusive', models.BooleanField(default=True, help_text='If True, displayed prices already include tax')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Store Settings',
                'verbose_name_plural': 'Store Settings',
            },
        ),
    ]
