# Generated by Django 4.2.11 on 2026-05-24 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_storesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storesettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='techzone/settings/'),
        ),
    ]
